name: Setup pnpm environment

description: setup pnpm environment and intall dependencies.

runs:
  using: "composite"
  steps:
    - name: Set pnpm version
      uses: pnpm/action-setup@v3
      with:
        version: 'latest'
        run_install: false

    - name: Install
      shell: bash
      run: |
        pnpm install
